# 1. Numpy

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)


array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [17]:
np.random.rand(2)

array([0.06801201, 0.23105965])

In [18]:
np.random.rand(5,5)

array([[0.38863889, 0.17527901, 0.21878226, 0.82031123, 0.07214153],
       [0.67802896, 0.82809357, 0.41919865, 0.4540991 , 0.64316285],
       [0.20471586, 0.25102178, 0.97075463, 0.07629172, 0.33261257],
       [0.59018719, 0.07317546, 0.74023613, 0.53536999, 0.59876823],
       [0.25325967, 0.15076921, 0.93804172, 0.52057973, 0.31917447]])

In [19]:
np.random.randn(2)

array([1.41328847, 1.13328669])

In [20]:
np.random.randn(5,5)

array([[-0.12627446,  0.13971145, -0.37835601, -0.24468361,  0.32281187],
       [ 1.32008563,  1.2418852 ,  1.00153922, -0.5506758 ,  1.46179468],
       [ 0.43783136, -1.45834044, -0.03777037,  1.95219891,  0.73444613],
       [-1.09648364,  1.34498681,  0.78349522, -1.22553847,  1.29897545],
       [-1.07252886, -1.24613673,  0.47734934, -0.0345013 , -0.66829114]])

In [21]:
np.random.randint(1,100)

4

In [22]:
np.random.randint(1,100,10)

array([89, 54, 16, 33, 10, 26,  3,  2, 27, 21])

In [23]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr

array([44, 38, 14,  2, 43, 26, 49, 32, 39, 32])

## Reshape
Returns an array containing the same data with a new shape.

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
ranarr.max()

49

In [30]:
#argmax means position of the max number
ranarr.argmax()

6

In [31]:
ranarr.min()

2

In [32]:
ranarr.argmin()

3

In [33]:
# Vector
arr.shape

(25,)

In [34]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [35]:
arr.reshape(1,25).shape

(1, 25)

### dtype

You can also grab the data type of the object in the array:

In [36]:
arr.dtype

dtype('int64')

# Numpy Array Indexing & Selection

In [2]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[7]

7

In [8]:
arr[1:5]

array([1, 2, 3, 4])

In [9]:
arr[:4]=100

In [29]:
arr

array([101, 101, 101, 101,   4,   5,   6,   7,   8,   9,  10])

In [41]:
arr=np.arange(11)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
slice_array = arr[:4]

In [44]:
slice_array[:]=101
slice_array

array([101, 101, 101, 101])

In [45]:
arr
#Now note the changes also occur in our original array!

array([101, 101, 101, 101,   4,   5,   6,   7,   8,   9,  10])

In [46]:
a = arr.copy()[:5]

In [47]:
a

array([101, 101, 101, 101,   4])

# 2d arrays

In [48]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [49]:
arr_2d[1]

array([20, 25, 30])

In [52]:
arr_2d[1][1]

25

In [53]:
arr_2d[1,1:]

array([25, 30])

In [54]:
arr_2d[1][1:]

array([25, 30])

In [56]:
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

### fancy indexing

In [63]:
new_array = np.zeros((10,5))
new_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [67]:
new_array.shape[0]

10

In [68]:
new_array.shape[1]

5

In [69]:
for i in range(new_array.shape[0]):
    new_array[i]=i
new_array

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9.]])

In [70]:
new_array[[1,5]]

array([[1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5.]])

In [2]:
import numpy as np
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [4]:
bool_arr = arr>4

In [5]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [6]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [7]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# operations on arrays

In [44]:
import numpy as np
numbers = np.arange(1,8)
numbers

array([1, 2, 3, 4, 5, 6, 7])

In [45]:
numbers + numbers

array([ 2,  4,  6,  8, 10, 12, 14])

In [46]:
numbers - numbers

array([0, 0, 0, 0, 0, 0, 0])

In [47]:
1/numbers

array([ 1.        ,  0.5       ,  0.33333333,  0.25      ,  0.2       ,
        0.16666667,  0.14285714])

In [48]:
res = np.sqrt(numbers**3)
res

array([  1.        ,   2.82842712,   5.19615242,   8.        ,
        11.18033989,  14.69693846,  18.52025918])

In [49]:
np.max(res)

18.520259177452136

In [50]:
res.min()

1.0

In [51]:
res.max()

18.520259177452136

In [52]:
np.sin(res)

array([ 0.84147098,  0.30807174, -0.88525077,  0.98935825, -0.98297934,
        0.84737646, -0.32337764])

In [53]:
np.max(numbers)

7

In [54]:
nu = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(numbers)
np.ceil(arr)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.])

In [55]:
np.floor(arr)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.])

In [56]:
np.rint(arr)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.])

## print options

In [57]:
print(np.floor(arr))
np.set_printoptions(sign=' ')
print(np.floor(arr))

[ 1.  2.  3.  4.  5.  6.  7.]
[ 1.  2.  3.  4.  5.  6.  7.]
