<a href="https://colab.research.google.com/github/Mohammad-H-Zahrawi/Data-Science-Python-Libraries/blob/master/python%2Bnumpy%2Bpandas%2Bmatplotlib/2_NumPy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Numpy

In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(3)


array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [ ]:
np.random.rand(2)

array([0.08946112, 0.88494252])

In [ ]:
np.random.rand(5,5)

array([[0.45704465, 0.03884997, 0.72987084, 0.45165044, 0.61306065],
       [0.18220284, 0.2501773 , 0.15886894, 0.60823318, 0.39317169],
       [0.28118245, 0.44718272, 0.17126916, 0.83282365, 0.08075122],
       [0.29650074, 0.2522272 , 0.94953933, 0.44991269, 0.38359559],
       [0.45009566, 0.39640215, 0.87868971, 0.28623966, 0.78906236]])

In [ ]:
np.random.randn(2)

array([ 0.03585866, -0.09368023])

In [ ]:
np.random.randn(5,5)

array([[ 0.26911398,  1.11771743, -1.42993732, -0.29767785, -0.75543385],
       [-1.47008845,  1.58317067, -0.01512929,  0.01081263, -0.80023257],
       [-0.70875531,  1.22477915,  0.53983638,  0.45930955, -0.10538696],
       [ 0.68191736,  1.17894872,  0.55305004,  1.12580528, -1.09980229],
       [ 0.51647649, -0.25253945, -0.99941941,  0.21792009,  1.43432137]])

In [ ]:
np.random.randint(1,100)

80

In [ ]:
np.random.randint(1,100,10)

array([87, 75, 64, 45, 77, 37, 63,  9, 59, 31])

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([26, 31, 15, 10, 18, 19,  4, 18,  9, 31])

## Reshape
Returns an array containing the same data with a new shape.

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr.max()

31

In [ ]:
#argmax means position of the max number
ranarr.argmax()

1

In [ ]:
ranarr.min()

4

In [ ]:
ranarr.argmin()

6

In [ ]:
# Vector
arr.shape

(25,)

In [ ]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

### dtype

You can also grab the data type of the object in the array:

In [ ]:
arr.dtype

dtype('int64')

# Numpy Array Indexing & Selection

In [ ]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[7]

7

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[:4]=100

In [ ]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
arr=np.arange(11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_array = arr[:4]

In [ ]:
slice_array[:]=101
slice_array

array([101, 101, 101, 101])

In [ ]:
arr
#Now note the changes also occur in our original array!

array([101, 101, 101, 101,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
a = arr.copy()[:5]

In [ ]:
a

array([101, 101, 101, 101,   4])

# 2d arrays

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [ ]:
arr_2d[1]

array([20, 25, 30])

In [ ]:
arr_2d[1][1]

25

In [ ]:
arr_2d[1,1:]

array([25, 30])

In [ ]:
arr_2d[1][1:]

array([25, 30])

In [ ]:
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

### fancy indexing

In [ ]:
new_array = np.zeros((10,5))
new_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
new_array.shape[0]

10

In [ ]:
new_array.shape[1]

5

In [ ]:
for i in range(new_array.shape[0]):
    new_array[i]=i
new_array

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9.]])

In [ ]:
new_array[[1,5]]

array([[1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5.]])

In [ ]:
import numpy as np
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr>4

In [ ]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# operations on arrays

In [ ]:
import numpy as np
numbers = np.arange(1,8)
numbers

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
numbers + numbers

array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
numbers - numbers

array([0, 0, 0, 0, 0, 0, 0])

In [ ]:
1/numbers

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714])

In [ ]:
res = np.sqrt(numbers**3)
res

array([ 1.        ,  2.82842712,  5.19615242,  8.        , 11.18033989,
       14.69693846, 18.52025918])

In [ ]:
np.max(res)

18.520259177452136

In [ ]:
res.min()

1.0

In [ ]:
res.max()

18.520259177452136

In [ ]:
np.sin(res)

array([ 0.84147098,  0.30807174, -0.88525077,  0.98935825, -0.98297934,
        0.84737646, -0.32337764])

In [ ]:
np.max(numbers)

7

In [ ]:
nu = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(numbers)
np.ceil(arr)

array([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
np.floor(arr)

array([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
np.rint(arr)

array([1., 2., 3., 4., 5., 6., 7.])

## print options

In [ ]:
print(np.floor(arr))
np.set_printoptions(sign=' ')
print(np.floor(arr))

[1. 2. 3. 4. 5. 6. 7.]
[ 1.  2.  3.  4.  5.  6.  7.]


## Others

In [ ]:
np.ones((3,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full((2,4),'M')
# Create a 2x4 array filled with 'M'

array([['M', 'M', 'M', 'M'],
       ['M', 'M', 'M', 'M']], dtype='<U1')

In [ ]:
np.random.random((3,3))

array([[ 0.86048091,  0.27375323,  0.17154715],
       [ 0.5625168 ,  0.57091304,  0.3506023 ],
       [ 0.15991856,  0.28296491,  0.48832884]])

In [ ]:
np.random.normal(0,10,(2,2))

array([[11.71272039, -6.01474711],
       [ 7.55303591, 14.30513921]])

In [ ]:
np.random.randint(1,11,(4,4))

array([[ 8,  3, 10,  9],
       [ 8, 10,  5,  4],
       [ 1,  7,  2,  1],
       [ 6,  3,  2,  3]])

In [ ]:
np.arange(1,120,5,dtype=np.int8)

array([  1,   6,  11,  16,  21,  26,  31,  36,  41,  46,  51,  56,  61,
        66,  71,  76,  81,  86,  91,  96, 101, 106, 111, 116], dtype=int8)

##The Basics of NumPy Arrays

In [ ]:
x1 = np.random.randint(0,10,size=6)
x1

array([6, 8, 0, 2, 0, 7])

In [ ]:
x2 = np.random.randint(0,10,(3,3))
x2

array([[4, 0, 2],
       [4, 8, 5],
       [4, 3, 6]])

In [ ]:
#the number of dimensions
x1.ndim

1

In [ ]:
#the number of dimensions
x2.ndim

2

In [ ]:
x2.shape

(3, 3)

In [ ]:
x2.size

9

In [ ]:
x2.dtype

dtype('int64')

In [ ]:
#size of each item
x2.itemsize

8

In [ ]:
#size of each array   8 x 9 = 72
x2.nbytes

72

In [ ]:
x1[-1]
#select last element

7

In [ ]:
x2[1][1]

8

In [ ]:
x2[1,1]

8

In [ ]:
#the value will be silently truncated.
x2[0][0]=2.99216669
x2

array([[2, 0, 2],
       [4, 8, 5],
       [4, 3, 6]])

In [ ]:
arr = np.arange(0,10)
x1

array([6, 8, 0, 2, 0, 7])

In [ ]:
arr[::2]
# every two numbers has been deleted
# 1 , 3 , 5 , 7 , 9

array([0, 2, 4, 6, 8])

In [ ]:
# every two numbers has been deleted starting from index 3
arr[3::2]

array([3, 5, 7, 9])

In [ ]:
arr[::-1]
# reverse array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
arr[7::-2]

array([7, 5, 3, 1])

In [ ]:
x2[:2,(0,2)]

array([[2, 2],
       [4, 5]])

In [ ]:
x2[::-1]

array([[4, 3, 6],
       [4, 8, 5],
       [2, 0, 2]])

In [ ]:
#select last column
x2[:,2]

array([2, 5, 6])

In [ ]:
#select the middle row
x2[1,:]

array([4, 8, 5])

#### reshape

In [ ]:
grid = np.arange(1,10)
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# convert 2d array to 1d.
grid.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# convert 2d array to 1d.
grid[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

##Array Concatenation and Splitting

In [ ]:
x = np.array([1,2,3,4])
y = np.array([6,7,8,9])

In [ ]:
np.concatenate([x,y])

array([1, 2, 3, 4, 6, 7, 8, 9])

In [ ]:
z = np.zeros(2,dtype=int)
np.concatenate([x,y,z])

array([1, 2, 3, 4, 6, 7, 8, 9, 0, 0])

In [ ]:
a  = np.array([1,2,3,4,5,6,7,8,9,11])

In [ ]:
sub1 , sub2  = np.split(a,2)

In [ ]:
sub1

array([1, 2, 3, 4, 5])

In [ ]:
sub2

array([ 6,  7,  8,  9, 11])

In [ ]:
a_2d = np.arange(24).reshape(4,6)
a_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
np.vsplit(a_2d,4)
#splite the array into 4 arrays, divide number of raws into 4/.

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23]])]

In [ ]:
left , right = np.hsplit(a_2d,2)
left
#splite the array into 2 arrays , divide number of cloumns into 2.

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])

In [ ]:
right

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23]])

In [ ]:
np.hsplit(a_2d,[4])
#splite the array into 2 arrays , divide number of cloumns into 2.

[array([[ 0,  1,  2,  3],
        [ 6,  7,  8,  9],
        [12, 13, 14, 15],
        [18, 19, 20, 21]]), array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]])]

In [ ]:
np.hsplit(a_2d,[4])
#splite the array into 2 arrays , divide number of cloumns into 2.

[array([[ 0,  1,  2,  3],
        [ 6,  7,  8,  9],
        [12, 13, 14, 15],
        [18, 19, 20, 21]]), array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]])]

## Universal Functions

In [ ]:
import numpy as np
arr = np.arange(5)

In [ ]:
arr + 5

array([5, 6, 7, 8, 9])

In [ ]:
arr = arr*-1
arr

array([ 0, -1, -2, -3, -4])

In [ ]:
abs(arr)

array([0, 1, 2, 3, 4])

In [ ]:
np.absolute(arr)

array([0, 1, 2, 3, 4])

In [ ]:
np.abs(arr)

array([0, 1, 2, 3, 4])

In [ ]:
theta = np.linspace(0,np.pi,5)
theta

array([ 0.        ,  0.78539816,  1.57079633,  2.35619449,  3.14159265])

In [ ]:
np.sin(theta)

array([ 0.00000000e+00,  7.07106781e-01,  1.00000000e+00,  7.07106781e-01,
        1.22464680e-16])

In [ ]:
np.tan(theta)

array([ 0.00000000e+00,  1.00000000e+00,  1.63312394e+16, -1.00000000e+00,
       -1.22464680e-16])

In [ ]:
alpha = np.array([-1,0,1])
np.arcsin(alpha)

array([-1.57079633,  0.        ,  1.57079633])

In [ ]:
np.arctan(alpha)

array([-0.78539816,  0.        ,  0.78539816])

In [ ]:
#natural logarithm
arr2 = np.array([1,2,4,10])
np.log(arr2)

array([ 0.        ,  0.69314718,  1.38629436,  2.30258509])

In [ ]:
#log 10
np.log10(arr2)

array([ 0.        ,  0.30103   ,  0.60205999,  1.        ])

In [ ]:
#e^x
np.exp(arr2)

array([ 2.71828183e+00,  7.38905610e+00,  5.45981500e+01,  2.20264658e+04])

In [ ]:
#natural logarithm
np.power(2,arr2)

array([   2,    4,   16, 1024])

In [ ]:
x = np.arange(5)
y = np.empty(5)
y

array([ 4.6775649e-310,  0.0000000e+000,  0.0000000e+000,  0.0000000e+000,
        0.0000000e+000])

In [ ]:
np.multiply(x, 10, out=y)
print(y)

[  0.  10.  20.  30.  40.]


In [ ]:
y=np.zeros(10)
np.multiply(x,10,out=y[::2])

array([  0.,  10.,  20.,  30.,  40.])

In [ ]:
y

array([  0.,   0.,  10.,   0.,  20.,   0.,  30.,   0.,  40.,   0.])

##Reduce

In [ ]:
x=np.arange(1,9)
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.add.reduce(x)

36

In [ ]:
np.multiply.reduce(x)

40320

In [ ]:
np.subtract.reduce(x)

-34

In [ ]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36])

In [ ]:
# create timetable
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  4,  6,  8, 10, 12, 14, 16],
       [ 3,  6,  9, 12, 15, 18, 21, 24],
       [ 4,  8, 12, 16, 20, 24, 28, 32],
       [ 5, 10, 15, 20, 25, 30, 35, 40],
       [ 6, 12, 18, 24, 30, 36, 42, 48],
       [ 7, 14, 21, 28, 35, 42, 49, 56],
       [ 8, 16, 24, 32, 40, 48, 56, 64]])

In [ ]:
# create timetable
np.add.outer(x[:5],x[:5])

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

## Aggregations: Min, Max, and Everything in Between

In [ ]:
L = np.random.randint(1,20,size=10)
print(L)
print('The summation of the array is',sum(L))
print('The minimum number in the array is ',min(L))
print('The maximum number in the array is ',np.max(L))
print('The product numbers in the array is ',np.product(L))
print('The standard deviation is',np.std(L))
print('The variance is',np.var(L))
print('The index of the maximum number is ',np.argmax(L))
print('The index of the minimum number is ',np.argmin(L))
print('The median is ',np.median(L))
print('The mean is ',np.mean(L))
print('evaluate whether any elements are true: ',np.any(L))
print('evaluate whether all elements are true: ',np.all(L))

# np.max() is much faster than max()

[10  1 19 19 14 15  8  3  6  2]
The summation of the array is 97
The minimum number in the array is  1
The maximum number in the array is  19
The product numbers in the array is  218332800
The standard deviation is 6.450581369148055
The variance is 41.61
The index of the maximum number is  2
The index of the minimum number is  1
The median is  9.0
The mean is  9.7
evaluate whether any elements are true:  True
evaluate whether all elements are true:  True


In [ ]:
print('first quartile', np.percentile(L, 25))
print('third quartile', np.percentile(L, 75))


first quartile 3.75
third quartile 14.75


In [ ]:
LL= np.random.randint(1,15,size=(3,4))
LL

array([[ 9,  6,  2, 13],
       [ 4,  1, 11, 11],
       [13,  9,  5, 13]])

In [ ]:
np.min(LL,axis=0)
# find the minimum in each column

array([ 4,  1,  2, 11])

In [ ]:
np.max(LL,axis=1)
# find the maximum in each row

array([13, 11, 13])

In [ ]:
np.product(LL)

5167871280

##broadcasting

In [ ]:
a = np.array([1,2,3])
b = np.array([15,16,17])
a+b

array([16, 18, 20])

In [ ]:
a + 3

array([4, 5, 6])

In [ ]:
M = np.ones((2,3))
M

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [ ]:
a+M

array([[ 2.,  3.,  4.],
       [ 2.,  3.,  4.]])

In [ ]:
y = np.arange(1,4).reshape(1,3)
z = np.arange(1,4).reshape(3,1)

In [ ]:
print(y)
print(z)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [ ]:
y + z

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
xx=np.linspace(0,50,6)
xxx=np.linspace(0,100,5).reshape(5,1)
print(xx)
print(xxx)

[  0.  10.  20.  30.  40.  50.]
[[   0.]
 [  25.]
 [  50.]
 [  75.]
 [ 100.]]


In [ ]:
z=xx+xxx
z

array([[   0.,   10.,   20.,   30.,   40.,   50.],
       [  25.,   35.,   45.,   55.,   65.,   75.],
       [  50.,   60.,   70.,   80.,   90.,  100.],
       [  75.,   85.,   95.,  105.,  115.,  125.],
       [ 100.,  110.,  120.,  130.,  140.,  150.]])

##Boolean

In [ ]:
a=np.array([1,2,3,4,5,6])

In [ ]:
a>4

array([False, False, False, False,  True,  True])

In [ ]:
a!=5

array([ True,  True,  True,  True, False,  True])

In [ ]:
x = np.random.randint(10, size=(3, 4))
x

array([[7, 1, 8, 4],
       [0, 1, 2, 7],
       [4, 1, 9, 4]])

In [ ]:
result = x>5
result

array([[ True, False,  True, False],
       [False, False, False,  True],
       [False, False,  True, False]])

In [ ]:
np.count_nonzero(result)

4

In [ ]:
#another way to count nonzero entries
np.sum(x>5)

4

In [ ]:
np.sum(x>5,axis=1)

array([2, 1, 1])

In [ ]:
print(np.any(x>8))
print(np.all(x>3))
print(np.any(x<0))
print(np.all(x>4,axis=0))

True
False
False
[False False False False]


In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sum((arr>4) & (arr<8))
# 5,6,7

3

In [ ]:
np.sum((arr>7) | (arr<4))
# 0,1,2,3,8,9

6

In [ ]:
s=np.sum(~((8>arr) & (arr>4)))
# 0,1,2,3,9
s

7

In [ ]:
arr[~((8>arr) & (arr>4))]

array([0, 1, 2, 3, 4, 8, 9])

In [ ]:
A = np.array([1,1,0,0])
B = np.array([1,0,0,1])
A | B

array([1, 1, 0, 1])

##fancy indexing

In [ ]:
x = np.random.randint(1,10,size=10)
x

array([2, 6, 8, 4, 9, 8, 8, 9, 7, 7])

In [ ]:
x[[1,3,5]]
#select the numbers in the following position. 1 , 3 , 5.

array([6, 4, 8])

In [ ]:
y = np.arange(12).reshape((3, 4))
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
y[row,col]

array([ 2,  5, 11])

In [ ]:
row = np.array([0, 1, 2]).reshape(3,1)
col = np.array([2, 1, 3])
y[row,col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [ ]:
y[2, [2, 0, 1]]

array([10,  8,  9])

In [ ]:
mask = np.array([1, 0, 1, 0], dtype=bool)
y[row.reshape(3,1), mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

##Example: Selecting Random Points

In [ ]:
mean = [0, 0]

In [ ]:
cov = [[1, 2],[2, 5]]

In [ ]:
rand = np.random.RandomState(42)
X = rand.multivariate_normal(mean, cov, 100)
X.shape

(100, 2)

In [ ]:
indices = np.random.choice(X.shape[0], 20, replace=False)
indices

array([94, 10, 18, 25, 26, 74, 40, 52, 38, 83, 65, 58, 39, 37, 16,  4, 69,
       32, 51, 27])

##Modifying Values with Fancy Indexing

In [ ]:
a = np.arange(10)
i=[1,2,3,8,9,1,1,1,1]
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[i]=55
a

array([ 0, 55, 55, 55,  4,  5,  6,  7, 55, 55])

In [ ]:
a[i]-=10
a

array([ 0, 45, 45, 45,  4,  5,  6,  7, 45, 45])

In [ ]:
x = np.zeros(10)
np.add.at(x, i, 5)
print(x)

[  0.  25.   5.   5.   0.   0.   0.   0.   5.   5.]


##Sorting Arrays

In [ ]:
arr = np.array([9,4,1,6,7,1,2,8,4])
arr.sort()
arr

array([1, 1, 2, 4, 4, 6, 7, 8, 9])

In [ ]:
arr2 = np.array([3,1,2,5,8,6])
np.sort(arr2)

array([1, 2, 3, 5, 6, 8])

In [ ]:
two_d = np.random.randint(1,10,size=(5,6))
two_d

array([[5, 6, 6, 4, 2, 9],
       [6, 3, 5, 2, 8, 8],
       [9, 9, 4, 7, 6, 3],
       [7, 9, 8, 3, 9, 8],
       [7, 5, 3, 4, 3, 1]])

In [ ]:
np.sort(two_d,axis=0)
#Sorting along coumns

array([[5, 3, 3, 2, 2, 1],
       [6, 5, 4, 3, 3, 3],
       [7, 6, 5, 4, 6, 8],
       [7, 9, 6, 4, 8, 8],
       [9, 9, 8, 7, 9, 9]])

In [ ]:
np.sort(two_d,axis=1)
#Sorting along raws

array([[2, 4, 5, 6, 6, 9],
       [2, 3, 5, 6, 8, 8],
       [3, 4, 6, 7, 9, 9],
       [3, 7, 8, 8, 9, 9],
       [1, 3, 3, 4, 5, 7]])

In [ ]:
a = np.array([20,55,12,10,66,11,40])
np.argsort(a)
#returns the indices of the sorted elements

array([3, 5, 2, 0, 6, 1, 4])

##Mohammad Zahrawi
##eng.moh.zahrawi@gmail.com