<a href="https://colab.research.google.com/github/Mohammad-H-Zahrawi/Data-Science-Python-Libraries/blob/master/python%2Bnumpy%2Bpandas%2Bmatplotlib/3_Pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Pandas 

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
pd.Series(data=5,index=[1,2,3])

1    5
2    5
3    5
dtype: int64

In [ ]:
arr = np.random.randint(1,10,size=(3,3))

df = pd.DataFrame(data=arr,index=['a','b','c'],columns=['First','Second','Third'])

In [ ]:
df

First  Second  Third
a      8       1      8
b      1       8      9
c      1       5      7

In [ ]:
df.loc['a']

First     8
Second    1
Third     8
Name: a, dtype: int32

In [ ]:
df.loc['a':'b']

First  Second  Third
a      4       4      6
b      9       6      8

In [ ]:
df.iloc[0]

First     4
Second    4
Third     6
Name: a, dtype: int64

In [ ]:
df['a':'b']

First  Second  Third
a      4       4      6
b      9       6      8

In [ ]:
df[0:2]

First  Second  Third
a      4       4      6
b      9       6      8

In [ ]:
df.ix[:2,'First':'Second']

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/ipykernel/__main__.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  if __name__ == '__main__':


First  Second
a      4       4
b      9       6

In [ ]:
df=pd.DataFrame(data=np.random.randint(0,10,(3,4)),columns=['a','s','d','f'])

In [ ]:
df

a  s  d  f
0  8  6  7  5
1  3  5  7  9
2  6  6  3  4

In [ ]:
df.sum(axis=1)

0    26
1    24
2    19
dtype: int64

In [ ]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])

In [ ]:
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [ ]:
A.add(B,fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [ ]:
df.mean()

a    5.666667
s    5.666667
d    5.666667
f    6.000000
dtype: float64

In [ ]:
df.stack().mean()
#total mean

5.75

# missing data

In [ ]:
arr = np.array([1,2,3,np.NaN])

In [ ]:
arr

array([ 1.,  2.,  3., nan])

In [ ]:
arr.sum()

nan

In [ ]:
np.nansum(arr)

6.0

In [ ]:
arr.dtype

dtype('float64')

#### None

In [ ]:
arr = np.array([1,2,3,None])
arr

array([1, 2, 3, None], dtype=object)

In [ ]:
arr.dtype

dtype('O')

#### operating on null values

In [ ]:
arr = np.array([[1,2,np.nan,4],[5,6,7,np.nan],[0,10,11,12]])
arr

array([[ 1.,  2., nan,  4.],
       [ 5.,  6.,  7., nan],
       [ 0., 10., 11., 12.]])

In [ ]:
arr1 = np.array([1,2,3,4,None])
arr1

array([1, 2, 3, 4, None], dtype=object)

In [ ]:
df = pd.DataFrame(arr,columns=['A','B','C','D'])
df

A     B     C     D
0  1.0   2.0   NaN   4.0
1  5.0   6.0   7.0   NaN
2  0.0  10.0  11.0  12.0

In [ ]:
df.isnull()

A      B      C      D
0  False  False   True  False
1  False  False  False   True
2  False  False  False  False

In [ ]:
df.notnull()
#opposite of isnull

A     B      C      D
0  True  True  False   True
1  True  True   True  False
2  True  True   True   True

In [ ]:
df.dropna(axis=0)

A     B     C     D
2  0.0  10.0  11.0  12.0

In [ ]:
df.dropna(axis=1)

A     B
0  1.0   2.0
1  5.0   6.0
2  0.0  10.0

In [ ]:
df.fillna(df.sum())

A     B     C     D
0  1.0   2.0  18.0   4.0
1  5.0   6.0   7.0  16.0
2  0.0  10.0  11.0  12.0

In [ ]:
df.fillna(method='bfill')

A     B     C     D
0  1.0   2.0   7.0   4.0
1  5.0   6.0   7.0  12.0
2  0.0  10.0  11.0  12.0

In [ ]:
df.fillna(method='ffill')

A     B     C     D
0  1.0   2.0   NaN   4.0
1  5.0   6.0   7.0   4.0
2  0.0  10.0  11.0  12.0

In [ ]:
df = pd.DataFrame(data=np.random.randint(0,10,size=(4,3)),columns=list('asd'))

In [ ]:
df

a  s  d
0  2  0  5
1  0  3  8
2  4  0  4
3  2  5  6

In [ ]:
df.describe()

a        s         d
count  4.000000  4.00000  4.000000
mean   2.000000  2.00000  5.750000
std    1.632993  2.44949  1.707825
min    0.000000  0.00000  4.000000
25%    1.500000  0.00000  4.750000
50%    2.000000  1.50000  5.500000
75%    2.500000  3.50000  6.500000
max    4.000000  5.00000  8.000000

In [ ]:
df.stack().count()

12

In [ ]:
df.unstack().count()

12

# Apply Filter Transform

In [ ]:
df = pd.DataFrame(data=[[1,2,3,'A'],[4,5,6,'B'],[7,8,9,'C'],[11,12,13,'A'],[14,15,16,'B'],[17,18,19,'C']],columns=['First','Second','Third','key'])

In [ ]:
df

First  Second  Third key
0      1       2      3   A
1      4       5      6   B
2      7       8      9   C
3     11      12     13   A
4     14      15     16   B
5     17      18     19   C

In [ ]:
df.groupby('key').sum()

First  Second  Third
key                      
A       12      14     16
B       18      20     22
C       24      26     28

In [ ]:
df.groupby('key').transform(lambda x:x-10)

First  Second  Third
0     -9      -8     -7
1     -6      -5     -4
2     -3      -2     -1
3      1       2      3
4      4       5      6
5      7       8      9

In [ ]:
def fun(x):
    return x['First'].sum()>15
df.groupby('key').filter(fun)

First  Second  Third key
1      4       5      6   B
2      7       8      9   C
4     14      15     16   B
5     17      18     19   C

# string with pandas

In [ ]:
data = pd.DataFrame(data = list([['Mohammad','Jordan','Male','054746663'],['Mung Kung','Korea','Male','0544625789'],['Sarah','Ireland','Female','054414763']]),columns=['Name','nationality','sex','phone'])
data

Name nationality     sex       phone
0   Mohammad      Jordan    Male   054746663
1  Mung Kung       Korea    Male  0544625789
2      Sarah     Ireland  Female   054414763

In [ ]:
data.get('Name')

0     Mohammad
1    Mung Kung
2        Sarah
Name: Name, dtype: object

In [ ]:
data['Name'].str.len()

0    8
1    9
2    5
Name: Name, dtype: int64

In [ ]:
data['Name'].str.slice(0,3)

0    Moh
1    Mun
2    Sar
Name: Name, dtype: object

In [ ]:
data['Name'].str.get_dummies()

Mohammad  Mung Kung  Sarah
0         1          0      0
1         0          1      0
2         0          0      1

In [ ]:
data['sex'].str.contains('Female')

0    False
1    False
2     True
Name: sex, dtype: bool

In [ ]:
data['sex'].str.contains('[Ma]ale').sum()
# looking for male ot Male

2

In [ ]:
data[data['sex']=='Male'].count()['sex']

2

# Others

In [ ]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
arr.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [ ]:
arr.transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [ ]:
arr=arr.reshape(2,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [ ]:
arr.transpose((2,1,0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [ ]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [ ]:
#cumsum
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [ ]:
arr.cumsum(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [ ]:
arr.cumprod(1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [ ]:
arr=np.array([1,5,4,7,8,0,1])
arr.sort()
arr

array([0, 1, 1, 4, 5, 7, 8])

In [ ]:
values = np.array([6, 0, 2, 5, 6])
np.in1d(values, [2, 3, 6])
# tests membership of the values in one array in another,
# returning a boolean array:

array([ True, False,  True, False,  True])

In [ ]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [ ]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [ ]:
df = pd.DataFrame(index=['a','b','c'],columns=['first','second','third'],data=np.arange(9).reshape(3,3))
df

first  second  third
a      0       1      2
b      3       4      5
c      6       7      8

In [ ]:
df.loc['a','first']

0

In [ ]:
df.loc[['a','c'],['first','second']]

first  second
a      0       1
c      6       7

In [ ]:
df.iloc[2]

first     6
second    7
third     8
Name: c, dtype: int64

In [ ]:
df['last']=[1,20,3]
df

first  second  third  last
a      0       1      2     1
b      3       4      5    20
c      6       7      8     3

In [ ]:
df.sort_index(axis='columns')

first  last  second  third
a      0     1       1      2
b      3    20       4      5
c      6     3       7      8

In [ ]:
df.sort_index(axis='columns',ascending=False)

third  second  last  first
a      2       1     1      0
b      5       4    20      3
c      8       7     3      6

In [ ]:
df.sort_values(by='last',ascending=True)

first  second  third  last
a      0       1      2     1
c      6       7      8     3
b      3       4      5    20

In [ ]:
df.sort_values(by=['last','third'],ascending=True)

first  second  third  last
a      0       1      2     1
c      6       7      8     3
b      3       4      5    20

In [ ]:
df


First  Second  Third
a      8       1      8
b      1       8      9
c      1       5      7

In [ ]:
df.isin([1])

First  Second  Third
a  False    True  False
b   True   False  False
c   True   False  False

In [ ]:
df.isin([1,20,7])
# are 1, 20, 7 in dataframe df?

First  Second  Third
a  False    True  False
b   True   False  False
c   True   False   True

In [ ]:
# read CSV
pd.options.display.max_rows = 10

In [ ]:
df.sort_values(['Third'])

First  Second  Third
c      1       5      7
a      8       1      8
b      1       8      9

In [ ]:
df.sort_values(['Second'])

First  Second  Third
a      8       1      8
c      1       5      7
b      1       8      9

In [ ]:
df['First'].value_counts()

1    2
8    1
Name: First, dtype: int64

In [ ]:
df.size

9