<a href="https://colab.research.google.com/github/Mohammad-H-Zahrawi/Data-Science-Python-Libraries/blob/master/python%2Bnumpy%2Bpandas%2Bmatplotlib/3_Pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Pandas 

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.Series(data=5,index=[1,2,3])

1    5
2    5
3    5
dtype: int64

In [3]:
arr = np.random.randint(1,10,size=(3,3))

df = pd.DataFrame(data=arr,index=['a','b','c'],columns=['First','Second','Third'])

In [4]:
df

First  Second  Third
a      4       4      1
b      5       6      5
c      8       6      7

In [5]:
df.loc['a']

First     4
Second    4
Third     1
Name: a, dtype: int64

In [6]:
df.loc['a':'b']

First  Second  Third
a      4       4      1
b      5       6      5

In [7]:
df.iloc[0]

First     4
Second    4
Third     1
Name: a, dtype: int64

In [8]:
df['a':'b']

First  Second  Third
a      4       4      1
b      5       6      5

In [19]:
df[0:2]

First  Second  Third
a      4       4      1
b      5       6      5

In [20]:
df.iloc[:2,[0,1]]

First  Second
a      4       4
b      5       6

In [21]:
df=pd.DataFrame(data=np.random.randint(0,10,(3,4)),columns=['a','s','d','f'])

In [22]:
df

a  s  d  f
0  2  7  7  9
1  5  2  4  7
2  8  8  5  7

In [23]:
df.sum(axis=1)

0    25
1    18
2    28
dtype: int64

In [24]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])

In [25]:
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [26]:
A.add(B,fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [27]:
df.mean()

a    5.000000
s    5.666667
d    5.333333
f    7.666667
dtype: float64

In [28]:
df.stack().mean()
#total mean

5.916666666666667

# missing data

In [29]:
arr = np.array([1,2,3,np.NaN])

In [30]:
arr

array([ 1.,  2.,  3., nan])

In [31]:
arr.sum()

nan

In [32]:
np.nansum(arr)

6.0

In [33]:
arr.dtype

dtype('float64')

#### None

In [34]:
arr = np.array([1,2,3,None])
arr

array([1, 2, 3, None], dtype=object)

In [35]:
arr.dtype

dtype('O')

#### operating on null values

In [36]:
arr = np.array([[1,2,np.nan,4],[5,6,7,np.nan],[0,10,11,12]])
arr

array([[ 1.,  2., nan,  4.],
       [ 5.,  6.,  7., nan],
       [ 0., 10., 11., 12.]])

In [37]:
arr1 = np.array([1,2,3,4,None])
arr1

array([1, 2, 3, 4, None], dtype=object)

In [38]:
df = pd.DataFrame(arr,columns=['A','B','C','D'])
df

A     B     C     D
0  1.0   2.0   NaN   4.0
1  5.0   6.0   7.0   NaN
2  0.0  10.0  11.0  12.0

In [39]:
df.isnull()

A      B      C      D
0  False  False   True  False
1  False  False  False   True
2  False  False  False  False

In [40]:
df.notnull()
#opposite of isnull

A     B      C      D
0  True  True  False   True
1  True  True   True  False
2  True  True   True   True

In [41]:
df.dropna(axis=0)

A     B     C     D
2  0.0  10.0  11.0  12.0

In [42]:
df.dropna(axis=1)

A     B
0  1.0   2.0
1  5.0   6.0
2  0.0  10.0

In [43]:
df.fillna(df.sum())

A     B     C     D
0  1.0   2.0  18.0   4.0
1  5.0   6.0   7.0  16.0
2  0.0  10.0  11.0  12.0

In [44]:
df.fillna(method='bfill')

A     B     C     D
0  1.0   2.0   7.0   4.0
1  5.0   6.0   7.0  12.0
2  0.0  10.0  11.0  12.0

In [45]:
df.fillna(method='ffill')

A     B     C     D
0  1.0   2.0   NaN   4.0
1  5.0   6.0   7.0   4.0
2  0.0  10.0  11.0  12.0

In [46]:
df = pd.DataFrame(data=np.random.randint(0,10,size=(4,3)),columns=list('asd'))

In [47]:
df

a  s  d
0  1  3  5
1  5  3  1
2  9  7  1
3  8  1  8

In [48]:
df.describe()

a         s        d
count  4.000000  4.000000  4.00000
mean   5.750000  3.500000  3.75000
std    3.593976  2.516611  3.40343
min    1.000000  1.000000  1.00000
25%    4.000000  2.500000  1.00000
50%    6.500000  3.000000  3.00000
75%    8.250000  4.000000  5.75000
max    9.000000  7.000000  8.00000

In [49]:
df.stack().count()

12

In [50]:
df.unstack().count()

12

# Apply Filter Transform

In [51]:
df = pd.DataFrame(data=[[1,2,3,'A'],[4,5,6,'B'],[7,8,9,'C'],[11,12,13,'A'],[14,15,16,'B'],[17,18,19,'C']],columns=['First','Second','Third','key'])

In [52]:
df

First  Second  Third key
0      1       2      3   A
1      4       5      6   B
2      7       8      9   C
3     11      12     13   A
4     14      15     16   B
5     17      18     19   C

In [53]:
df.groupby('key').sum()

First  Second  Third
key                      
A       12      14     16
B       18      20     22
C       24      26     28

In [54]:
df.groupby('key').transform(lambda x:x-10)

First  Second  Third
0     -9      -8     -7
1     -6      -5     -4
2     -3      -2     -1
3      1       2      3
4      4       5      6
5      7       8      9

In [55]:
def fun(x):
    return x['First'].sum()>15
df.groupby('key').filter(fun)

First  Second  Third key
1      4       5      6   B
2      7       8      9   C
4     14      15     16   B
5     17      18     19   C

# string with pandas

In [56]:
data = pd.DataFrame(data = list([['Mohammad','Jordan','Male','054746663'],['Mung Kung','Korea','Male','0544625789'],['Sarah','Ireland','Female','054414763']]),columns=['Name','nationality','sex','phone'])
data

Name nationality     sex       phone
0   Mohammad      Jordan    Male   054746663
1  Mung Kung       Korea    Male  0544625789
2      Sarah     Ireland  Female   054414763

In [57]:
data.get('Name')

0     Mohammad
1    Mung Kung
2        Sarah
Name: Name, dtype: object

In [58]:
data['Name'].str.len()

0    8
1    9
2    5
Name: Name, dtype: int64

In [59]:
data['Name'].str.slice(0,3)

0    Moh
1    Mun
2    Sar
Name: Name, dtype: object

In [60]:
data['Name'].str.get_dummies()

Mohammad  Mung Kung  Sarah
0         1          0      0
1         0          1      0
2         0          0      1

In [61]:
data['sex'].str.contains('Female')

0    False
1    False
2     True
Name: sex, dtype: bool

In [62]:
data['sex'].str.contains('[Ma]ale').sum()
# looking for male ot Male

2

In [63]:
data[data['sex']=='Male'].count()['sex']

2

# Others

In [64]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
arr.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [66]:
arr.transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [67]:
arr=arr.reshape(2,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [68]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [69]:
arr.transpose((2,1,0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [70]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [71]:
#cumsum
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [73]:
arr.cumsum(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [74]:
arr.cumprod(1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [75]:
arr=np.array([1,5,4,7,8,0,1])
arr.sort()
arr

array([0, 1, 1, 4, 5, 7, 8])

In [76]:
values = np.array([6, 0, 2, 5, 6])
np.in1d(values, [2, 3, 6])
# tests membership of the values in one array in another,
# returning a boolean array:

array([ True, False,  True, False,  True])

In [77]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [78]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [79]:
df = pd.DataFrame(index=['a','b','c'],columns=['first','second','third'],data=np.arange(9).reshape(3,3))
df

first  second  third
a      0       1      2
b      3       4      5
c      6       7      8

In [80]:
df.loc['a','first']

0

In [81]:
df.loc[['a','c'],['first','second']]

first  second
a      0       1
c      6       7

In [82]:
df.iloc[2]

first     6
second    7
third     8
Name: c, dtype: int64

In [83]:
df['last']=[1,20,3]
df

first  second  third  last
a      0       1      2     1
b      3       4      5    20
c      6       7      8     3

In [84]:
df.sort_index(axis='columns')

first  last  second  third
a      0     1       1      2
b      3    20       4      5
c      6     3       7      8

In [85]:
df.sort_index(axis='columns',ascending=False)

third  second  last  first
a      2       1     1      0
b      5       4    20      3
c      8       7     3      6

In [86]:
df.sort_values(by='last',ascending=True)

first  second  third  last
a      0       1      2     1
c      6       7      8     3
b      3       4      5    20

In [87]:
df.sort_values(by=['last','third'],ascending=True)

first  second  third  last
a      0       1      2     1
c      6       7      8     3
b      3       4      5    20

In [88]:
df


first  second  third  last
a      0       1      2     1
b      3       4      5    20
c      6       7      8     3

In [89]:
df.isin([1])

first  second  third   last
a  False    True  False   True
b  False   False  False  False
c  False   False  False  False

In [90]:
df.isin([1,20,7])
# are 1, 20, 7 in dataframe df?

first  second  third   last
a  False    True  False   True
b  False   False  False   True
c  False    True  False  False

In [91]:
# read CSV
pd.options.display.max_rows = 10

In [97]:
df.sort_values(by=['third'])

first  second  third  last
a      0       1      2     1
b      3       4      5    20
c      6       7      8     3

In [98]:
df.sort_values(['second'])

first  second  third  last
a      0       1      2     1
b      3       4      5    20
c      6       7      8     3

In [99]:
df['first'].value_counts()

3    1
6    1
0    1
Name: first, dtype: int64

In [100]:
df.size

12